init

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -1,6 +1,16 @@
 #!/bin/bash
 
+
 # emerge
-sudo emerge --sync || (nmcli c up $DEF_VPN && sudo emerge --sync)
-sudo emerge --update --deep --changed-use @world
-sudo smart-live-rebuild
+EMERGE_ARGS="-q"
+EMERGE="emerge $EMERGE_ARGS"
+sudo $EMERGE --depclean
+(sudo $EMERGE --sync || (nmcli c up $DEF_VPN && sudo $EMERGE --sync)) && sudo $EMERGE --update --deep --changed-use @world || FAILED_UPDATE=1
+sudo smart-live-rebuild -q
+sudo $EMERGE --depclean
+if [[ $FAILED_UPDATE == 1 ]] ; then echo "-------Update failed--------" ; fi
+
+
+# git
+## oh-my-zsh
+cd $HOME/.oh-my-zsh && git pull || ( git stash && git pull )
